export default {
  Assembly: {
    Type: [
      'Reduced Pressure (RP)',
      'Reduced Pressure Detector (RPDA)',
      'Double Check (DC)',
      'Double Check Detector (DCDA)',
      'Pressure Vacuum Breaker (PVB)',
      'Spill-Resistant Pressure Vacuum Breaker (SRPVB)',
      'Air Gap (AG)',
    ],
    Manufacturer: [
      'Ames',
      'Apollo / Conbraco',
      'ARI',
      'Backflow Direct',
      'Cash Acme',
      'Cla - Val',
      'Febco',
      'Flomatic',
      'Hersey',
      'Neptune',
      'Watts',
      'Wilkins',
    ],
    Size: [
      '0.25',
      '0.375',
      '0.50',
      '0.75',
      '1.0',
      '1.25',
      '1.5',
      '2.0',
      '2.5',
      '3.0',
      '4.0',
      '6.0',
      '8.0',
      '10.0',
      '12.0',
    ],
  },
};
