export const notification = {
  NotificationNo: '',
  NotificationDate: '',
  CustomerName: '',
  Telephone: '',
  City: '',
  DueDate: '',
  Street: '',
  NotificationCheckDigit: '',
  AssemblyType: '',
  AssemblyTypeDscrpt: '',
  Size: '',
  Manufacturer: '',
  SerialNo: '',
  ModelNo: '',
  FirelineFlushRequired: '',
  FirelineFlushReqDscrpt: '',
  Location: '',
  HazardCode: '',
  HazardCodeDscrpt: '',
};

export const tester = {
  TestComments: '',
  TesterFirstName: '',
  TesterLastName: '',
  TesterPhone: '',
  TesterCertificationNo: '',
  TesterCertificationExpDate: '',
  TesterCompanyName: '',
  TesterCompanyPhone: '',
  TesterCompanyFax: '',
  TesterEmail: '',
};
